# Generated by Django 2.2.16 on 2020-09-25 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('kms', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Personas',
            },
        ),
    ]
